Aditya/appointment options
gaurav7891/covid19vaccinetracker pull request #5
Opened 2021-05-10 17:20 UTC by Aditya-Bhandare

1. Migrated from activity to fragment for HomeActivity.
2. Updated onCreateOptionMenu for both fragments
3. Resolved conflicts from Master branch

2021-05-14 13:14 UTC, gaurav7891 requested changes

2021-05-14 13:14 UTC, gaurav7891 commented on app/src/main/AndroidManifest.xml
> +        <activity android:name=".MainActivity" android:launchMode="singleTask" />
Please revert this if we are done with the changes for fragment implementation

2021-05-14 13:14 UTC, gaurav7891 commented on app/src/main/java/com/nativework/covid19vaccinetracker/base/BaseApp.kt
> +  /*  override fun onBackPressed() {
remove the unwanted code

2021-05-14 13:14 UTC, gaurav7891 commented on app/src/main/java/com/nativework/covid19vaccinetracker/ui/HomeActivity.kt
> +                loadFragment(HomeFragment(), R.id.home_container)
Please change the name with some meaningFul class name, based on responsibilty of the class, HomeFragmemt() and AppointmentFragment doesnt match well

2021-05-14 13:14 UTC, gaurav7891 commented on app/src/main/java/com/nativework/covid19vaccinetracker/ui/appointment/AppointmentFragment.kt
> +        if (!pin.isNullOrEmpty()) {
condition can be simplified as pin.isNotEmpty()

2021-05-14 13:14 UTC, gaurav7891 commented on app/src/main/res/values/strings.xml
>      <string name="hello_blank_fragment">Hello blank fragment</string>
remove this string

2021-05-14 15:47 UTC, Aditya-Bhandare commented on app/src/main/java/com/nativework/covid19vaccinetracker/ui/HomeActivity.kt
> +                loadFragment(HomeFragment(), R.id.home_container)
Changed to CalenderByDistrictFragment() and CalenderByPincodeFragment()

2021-05-15 02:28 UTC, gaurav7891 approved these changes

2021-05-15 02:28 UTC, merged